server:
  port: 8080
spring:
  datasource:
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
  liquibase:
    change-log: classpath:liquibase/master.xml
